### ISSUE TITLE
docker-compose.yml has variables not supported by version 3

### ISSUE THREAD

**Issue by Shadowghost** [hackmdio/docker-hackmd#59]
Seems like some variables implemented with #57 are not compatible with the used version of `docker-compose.yml`. As writte [here](https://docs.docker.com/compose/compose-file/compose-versioning/#upgrading) the variables `mem_limit` and `memswap_limit` are deprecated and can not be used on v3. 
It seems to be possible to keep some fuctionality by configuring the services with deploy-variables.
This should result in something like this:
```
version: '3'
services:
  database:
    image: postgres:9.6-alpine
    deploy:
      resources:
        limits:
          memory: 256M
```
